/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author USER
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuMConfiguracion = new javax.swing.JMenu();
        mnuPerfil = new javax.swing.JMenuItem();
        mnuEspecialidad = new javax.swing.JMenuItem();
        mnuTurno = new javax.swing.JMenuItem();
        mnuTipoDocumento = new javax.swing.JMenuItem();
        mnuGenero = new javax.swing.JMenuItem();
        mnuDistrito = new javax.swing.JMenuItem();
        mnuMPersonal = new javax.swing.JMenu();
        mnuPersonal = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenuItem();
        mnuMPaciente = new javax.swing.JMenu();
        mnuPPaciente = new javax.swing.JMenuItem();
        mnuCitaMedica = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/usuario_ico.jpg"))); // NOI18N

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        mnuMConfiguracion.setText("Configuración");

        mnuPerfil.setText("Perfil");
        mnuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPerfilActionPerformed(evt);
            }
        });
        mnuMConfiguracion.add(mnuPerfil);

        mnuEspecialidad.setText("Especialidad");
        mnuEspecialidad.setToolTipText("");
        mnuEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEspecialidadActionPerformed(evt);
            }
        });
        mnuMConfiguracion.add(mnuEspecialidad);

        mnuTurno.setText("Turno");
        mnuTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTurnoActionPerformed(evt);
            }
        });
        mnuMConfiguracion.add(mnuTurno);

        mnuTipoDocumento.setText("Tipo de documento");
        mnuTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipoDocumentoActionPerformed(evt);
            }
        });
        mnuMConfiguracion.add(mnuTipoDocumento);

        mnuGenero.setText("Género");
        mnuGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGeneroActionPerformed(evt);
            }
        });
        mnuMConfiguracion.add(mnuGenero);

        mnuDistrito.setText("Distrito");
        mnuDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDistritoActionPerformed(evt);
            }
        });
        mnuMConfiguracion.add(mnuDistrito);

        jMenuBar1.add(mnuMConfiguracion);

        mnuMPersonal.setText("Personal");

        mnuPersonal.setText("Personal");
        mnuPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPersonalActionPerformed(evt);
            }
        });
        mnuMPersonal.add(mnuPersonal);

        mnuUsuario.setText("Usuario");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        mnuMPersonal.add(mnuUsuario);

        jMenuBar1.add(mnuMPersonal);

        mnuMPaciente.setText("Paciente");

        mnuPPaciente.setText("Paciente");
        mnuPPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPPacienteActionPerformed(evt);
            }
        });
        mnuMPaciente.add(mnuPPaciente);

        mnuCitaMedica.setText("Cita Médica");
        mnuCitaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCitaMedicaActionPerformed(evt);
            }
        });
        mnuMPaciente.add(mnuCitaMedica);

        jMenuBar1.add(mnuMPaciente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPerfilActionPerformed
        // TODO add your handling code here:
        frmPerfil regPerfil = new frmPerfil();
        this.Escritorio.add(regPerfil);
        regPerfil.show();
    }//GEN-LAST:event_mnuPerfilActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEspecialidadActionPerformed
        // TODO add your handling code here:
        frmEspecialidad regEspecialidad = new frmEspecialidad();
        this.Escritorio.add(regEspecialidad);
        regEspecialidad.show();
    }//GEN-LAST:event_mnuEspecialidadActionPerformed

    private void mnuTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTurnoActionPerformed
        // TODO add your handling code here:
        frmTurno regTurno = new frmTurno();
        this.Escritorio.add(regTurno);
        regTurno.show();
    }//GEN-LAST:event_mnuTurnoActionPerformed

    private void mnuTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipoDocumentoActionPerformed
        // TODO add your handling code here:
        frmTipoDocumento regTipoDocumento = new frmTipoDocumento();
        this.Escritorio.add(regTipoDocumento);
        regTipoDocumento.show();
    }//GEN-LAST:event_mnuTipoDocumentoActionPerformed

    private void mnuGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGeneroActionPerformed
        // TODO add your handling code here:
        frmGenero regGenero = new frmGenero();
        this.Escritorio.add(regGenero);
        regGenero.show();
    }//GEN-LAST:event_mnuGeneroActionPerformed

    private void mnuDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDistritoActionPerformed
        // TODO add your handling code here:
        frmDistrito regDistrito = new frmDistrito();
        this.Escritorio.add(regDistrito);
        regDistrito.show();
    }//GEN-LAST:event_mnuDistritoActionPerformed

    private void mnuPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPersonalActionPerformed
        // TODO add your handling code here:
        frmPersonal regPersonal = new frmPersonal();
        this.Escritorio.add(regPersonal);
        regPersonal.show();
    }//GEN-LAST:event_mnuPersonalActionPerformed

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        // TODO add your handling code here:
        frmUsuario regUsuario = new frmUsuario();
        this.Escritorio.add(regUsuario);
        regUsuario.show();
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuCitaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCitaMedicaActionPerformed
        // TODO add your handling code here:
        frmCita regCita = new frmCita();
        this.Escritorio.add(regCita);
        regCita.show();
    }//GEN-LAST:event_mnuCitaMedicaActionPerformed

    private void mnuPPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPPacienteActionPerformed
        // TODO add your handling code here:
        frmPaciente regPaciente = new frmPaciente();
        this.Escritorio.add(regPaciente);
        regPaciente.show();
    }//GEN-LAST:event_mnuPPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmMenu().setVisible(true);
                frmMenu menu = new frmMenu();
                menu.setExtendedState(MAXIMIZED_BOTH);
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCitaMedica;
    private javax.swing.JMenuItem mnuDistrito;
    private javax.swing.JMenuItem mnuEspecialidad;
    private javax.swing.JMenuItem mnuGenero;
    private javax.swing.JMenu mnuMConfiguracion;
    private javax.swing.JMenu mnuMPaciente;
    private javax.swing.JMenu mnuMPersonal;
    private javax.swing.JMenuItem mnuPPaciente;
    private javax.swing.JMenuItem mnuPerfil;
    private javax.swing.JMenuItem mnuPersonal;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuTipoDocumento;
    private javax.swing.JMenuItem mnuTurno;
    private javax.swing.JMenuItem mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
